#!/usr/bin/env python
# coding=utf-8

import os.path
import sys
import traceback

sys.path = ([sys.path[0]]
            + [os.path.join(os.path.dirname(__file__), "../lib")]
            + sys.path[1:])
import dataprocessor as dp
sys.path = [sys.path[0]] + sys.path[2:]


def main():
    parser = dp.argparsers.dataprocessor()
    args = parser.parse_args()

    json_fn = dp.utility.abspath(args.manip_json)
    dp.utility.check_file(json_fn)
    if args.data:
        data_fn = dp.utility.abspath(args.data)
        with open(json_fn, 'r') as f, dp.io.SyncDataHandler(data_fn,
                                                            duration=1) as dh:
            dp.execute.execute_from_json_str(f.read(), dh.get())
    else:
        with open(json_fn, 'r') as f:
            dp.execute.execute_from_json_str(f.read())


if __name__ == "__main__":
    try:
        main()
    except dp.exception.InvalidJSONError as e:
        print("ERROR found in your JSON")
        print("Pipe name: %s" % e.name)
        print("Message  : %s" % e.msg)
        sys.exit(1)
    except dp.exception.DataProcessorError as e:
        print(traceback.format_exc())
        print("ERROR in command-line arguments.")
        print("Message: %s" % e.msg)
        sys.exit(1)
